name: CI
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Run unit tests
        run: |
          pytest

      - name: Run performance benchmarks
        run: |
          pytest test_performance_doolittle.py --benchmark-only --benchmark-json=wyniki_benchmark.json

      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: wyniki_benchmark.json
